id: P009180
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01648
  title: བཅོམ་ལྡན་འདས་དུས་ཀྱི་འཁོར་ལོ་ལྷན་སྐྱེས་ཀྱི་རྒྱུན་ཁྱེར་དང་རྣལ་འབྱོར་ཡན་ལག་དྲུག་པ་སྟན་ཐོག་གཅིག་པའི་དམིགས་སྡོམ་ལྷན་སྐྱེས་གྲུབ་སྟེར
  author: ''
  volumes: {}
