id: P009180
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG01648
  title: བཅོམ་ལྡན་འདས་དུས་ཀྱི་འཁོར་ལོ་ལྷན་སྐྱེས་ཀྱི་རྒྱུན་ཁྱེར་དང་རྣལ་འབྱོར་ཡན་ལག་དྲུག་པ་སྟན་ཐོག་གཅིག་པའི་དམིགས་སྡོམ་ལྷན་སྐྱེས་གྲུབ་སྟེར
  author: ''
  volumes:
    c5c4308708364a798c26a5c41c7e82a6:
      image_group_id: I00KG02955
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
